### PR TITLE
Represent contig ids as int32 rather than int16

### LINKED ISSUE #10: loading bam with many contigs (~2^16) fails
Contigs ids are represented as an int16, which fails for bams aligned to a large number of contigs (e.g. transcriptome alignments). This looks like an easy fix and I can submit a PR.

```
~/anaconda3/lib/python3.8/site-packages/bamread/read.py in read_bam_full(f, mapq, required_flag, filter_flag)
     26 def read_bam_full(f, mapq=0, required_flag=0, filter_flag=1540):
     27 
---> 28     chromosomes, starts, ends, strands, flags, chrmap, qstarts, qends, query_names, query_sequences, cigarstrings, query_qualities = _bamread_all(
     29         f, mapq, required_flag, filter_flag)
     30 

~/anaconda3/lib/python3.8/site-packages/bamread/src/bamread.pyx in bamread.src.bamread._bamread_all()

~/anaconda3/lib/python3.8/site-packages/bamread/src/bamread.pyx in bamread.src.bamread._bamread_all()

OverflowError: value too large to convert to int16_t

### PR DESCRIPTION
**Pull request by timodonnell**
Closes #10

### CODE REVIEW

**Comment by endrebak** [comment]
Thanks, will look at tomorrow :)

**Comment by RPHdejongh** [comment]
I have a genome with many contigs, for which I'd like to read in a bamfile, can this PR be merged?

**Comment by endrebak** [comment]
I'll look at this on Monday :)

**Comment by catsargent** [comment]
I also came across this issue with the chimp reference genome. Would have been great if this PR had been merged!

**Comment by endrebak** [comment]
I’ll fix it

**Comment by endrebak** [comment]
Fixed. Credited you in the CHANGELOG.

**Pull request closed without merging**
