### PR TITLE
Include query sequences in read_bam_full

### LINKED ISSUE #3: feature request: include sequences
Thanks for a great library. It would be very helpful as a general purpose tool if `bamread.read_bam_full` had the ability to include the query sequences.

### PR DESCRIPTION
**Pull request by timodonnell**
Fixes #3

### CODE REVIEW

**Comment by endrebak** [comment]
I had actually gotten the sequences in my cython code, but forgotten to include them in my python code.

**Comment by endrebak** [comment]
0.0.7 out on pypi. Thanks!

Are you using bamread as a standalone library? I guess it isn't very user-friendly, but I thought people would be using it from pyranges so I haven't polished it much.

**Comment by timodonnell** [comment]
Thanks! Yeah, I've been using it standalone. I think there is space for a reasonably performant way to read BAMs into a pandas dataframe without a big (and ever changing) API like pysam. This project could be that!

**Comment by endrebak** [comment]
Thanks. If you have suggestions for an API you'd like I'm likely to
implement some variation of it.

**Comment by timodonnell** [comment]
Sure, I'll make a ticket with thoughts on an API

**Pull request merged**
